cardgame/cardgame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

cardgame/core/urls.py
from django.urls import path
from core.views import (CardListView, UserListView,
                        GameView, GameDetailView,
                        DrawCardView)


urlpatterns = [
    path('cards/', CardListView.as_view(), name='cards'),
    path('users/', UserListView.as_view(), name='cards'),
    path('games/', GameView.as_view(), name='cards'),
    path('games/<slug:pk>', GameDetailView.as_view(), name='cards'),
    path('draw_card/', DrawCardView.as_view(), name='cards'),

]

cardgame/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from core.managers import UserManager
from enum import Enum


class User(AbstractBaseUser, PermissionsMixin):
    """ Custom player model that supports using email instead of username """

    username = models.CharField(unique=True, max_length=20)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    class Meta:
        ordering = ('id', )

    def __str__(self):
        """
        Returns a string representation of this `User`.

        This string is used when a `User` is printed in the console.
        """
        return self.username


class Suit(Enum):
    SPADE = "Spades"
    CLUB = "Clubs"
    DIAMOND = "Diamond"
    HEART = "Heart"
    EXTRA = "Extra"


class Card(models.Model):
    suit = models.CharField(
        max_length=10,
        choices=[(tag.name, tag.value) for tag in Suit],
        default=Suit.EXTRA.name
    )
    rank = models.CharField(max_length=5)

    def __str__(self):
        return f'{self.suit} - {self.rank}'


class GameStatus(Enum):
    """Enum for different types of topic"""

    NR = "No Result"
    W = "Won"
    D = "Draw"


class Game(models.Model):
    player1 = models.ForeignKey(User, on_delete=models.DO_NOTHING,
                                related_name="player1")
    player2 = models.ForeignKey(User, on_delete=models.DO_NOTHING,
                                related_name="player2")
    next_move_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                     related_name='move_by', blank=True,
                                     null=True)
    status = models.CharField(
        max_length=3,
        choices=[(tag.name, tag.value) for tag in GameStatus],
        default=GameStatus.NR.name
    )
    won_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=None,
                               null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'game b/w {self.player1} & {self.player2}'


class CardSequence(models.Model):
    player = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Card - {self.card} drawn by {self.player}'

cardgame/templates/card_detail.html
{% extends "parent.html" %}

{% block title %}
Card List
{% endblock %}

{% block body %}
    {{card}}
{% endblock %}

cardgame/templates/cards.html
{% extends "parent.html" %}

{% block title %}
Card List
{% endblock %}

{% block body %}
    <h1>Card List</h1>
    {% if card_list %}
        <ul>
    {% for card in card_list %}
      <li>
        <a href="{{ card.get_absolute_url }}">{{ card.suit }} -  {{card.rank}}</a>
      </li>
    {% endfor %}
    </ul>
    {% else %}
        <p>There are no cards in the deck.</p>
    {% endif %}
{% endblock %}

cardgame/templates/index.html
{% extends "parent.html" %}

{% block title %}
Home
{% endblock %}

{% block body %}
    <h1>Welcome to GLCardGame</h1><br>

{% endblock %}

cardgame/templates/parent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - YouTube Clone</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
</head>
<body>
          {% block body %}
          {% endblock %}
</body>
</html>